version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: petitlink-proxy
    depends_on:
      - auth
      - web
      - api

  auth:
    build:
      context: ./petitlink/auth
      dockerfile: Dockerfile
    env_file:
      - ./petitlink/auth/.env
    expose:
      - "8001"
    volumes:
      - ./petitlink/auth/:/auth/

  web:
    build:
      context: petitlink/web
      dockerfile: Dockerfile
    env_file:
      - petitlink/web/.env
    expose:
      - "8000"
    volumes:
      - ./petitlink/web/:/web/

  api:
    build:
      context: ./petitlink/api
      dockerfile: Dockerfile
    env_file:
      - ./petitlink/api/.env
    expose:
      - "8002"
    volumes:
      -  ./petitlink/api/:/api/
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - "6379"
    restart: always