version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: petitlink-proxy
    depends_on:
      - auth

  auth:
    build:
      context: ./petitlink/auth
      dockerfile: Dockerfile
    env_file:
      - ./petitlink/auth/.env
    expose:
      - "8001"

  web:
    build:
      context: petitlink/web
      dockerfile: Dockerfile
    env_file:
      - petitlink/web/.env
    expose:
      - "8000"