[tool.poetry]
name = "practice001"
version = "0.1.0"
description = ""
authors = ["Jim Jeon <jimjeon.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
